In [46]:
from sklearn.svm import SVC
from sklearn import svm
import numpy as np

In [47]:
X=np.array([[3,4],[1,4],[2,3],[6,-1],[7,-1],[5,-3]])
y=np.array([-1,-1,-1,1,1,1])

In [48]:
l=SVC(C=1e5,kernel='linear')
l.fit(X,y)

SVC(C=100000.0, kernel='linear')

In [49]:
print('w= ',l.coef_)
print('b= ',l.intercept_)
print('Indices of support vectors= ',l.support_)
print('Support vectors= ',l.support_vectors_)
print('No. of support vectors from each class= ',l.n_support_)
print('coefficient of support vectors in decision function= ',np.abs(l.dual_coef_))


w=  [[ 0.25 -0.25]]
b=  [-0.75]
Indices of support vectors=  [2 3]
Support vectors=  [[ 2.  3.]
 [ 6. -1.]]
No. of support vectors from each class=  [1 1]
coefficient of support vectors in decision function=  [[0.0625 0.0625]]


In [50]:
import pandas as pd
data=pd.read_csv('glass.csv')
data.head()

RI     Na    Mg    Al     Si     K    Ca   Ba   Fe  Type
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [51]:
x=data.drop('Type',axis=1)
y=data.Type

In [52]:

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [53]:
linear=svm.SVC(kernel='linear')
linear.fit(x_train,y_train)

SVC(kernel='linear')

In [54]:
print(linear.support_vectors_)

[[ 1.51779 13.21     3.39    ...  8.59     0.       0.     ]
 [ 1.51769 12.45     2.71    ...  9.06     0.       0.24   ]
 [ 1.51898 13.58     3.35    ...  8.91     0.       0.     ]
 ...
 [ 1.51727 14.7      0.      ...  8.95     0.66     0.     ]
 [ 1.51623 14.2      0.      ...  9.04     0.4      0.09   ]
 [ 1.51545 14.14     0.      ...  9.07     0.61     0.05   ]]


In [55]:
print(linear.n_support_)

[45 48 12  9  5 10]


In [56]:
y_pred=linear.predict(x_test)

In [57]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))


0.676923076923077


In [58]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))

[[16  2  0  0  0  0]
 [ 6 16  0  0  2  0]
 [ 4  1  0  0  0  0]
 [ 0  1  0  1  0  0]
 [ 0  2  0  1  1  0]
 [ 0  0  0  1  1 10]]


In [59]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))


              precision    recall  f1-score   support

           1       0.62      0.89      0.73        18
           2       0.73      0.67      0.70        24
           3       0.00      0.00      0.00         5
           5       0.33      0.50      0.40         2
           6       0.25      0.25      0.25         4
           7       1.00      0.83      0.91        12

    accuracy                           0.68        65
   macro avg       0.49      0.52      0.50        65
weighted avg       0.65      0.68      0.65        65



/home/ignis/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ignis/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ignis/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [60]:
model1=SVC(kernel='sigmoid')
model2=SVC(kernel='poly')
model3=SVC(kernel='rbf')



In [61]:
model1.fit(x_train,y_train)
model2.fit(x_train,y_train)
model3.fit(x_train,y_train)

SVC()

In [62]:
y_pred1=model1.predict(x_test)
y_pred2=model2.predict(x_test)
y_pred3=model3.predict(x_test)

In [63]:
print("prediction by model1 ",accuracy_score(y_test,y_pred1))
print("prediction by model2",accuracy_score(y_test,y_pred2))
print("prediction by model3",accuracy_score(y_test,y_pred1))


prediction by model1  0.3384615384615385
prediction by model2 0.3384615384615385
prediction by model3 0.3384615384615385
